version: "3.9"
   
services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    image: nginx:1.23-alpine
    volumes:
        - ./static:/usr/share/nginx/html/static:ro
        # Templates are used to create config files - see https://hub.docker.com/_/nginx
        - ./nginx-templates:/etc/nginx/templates:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - web
